### ISSUE TITLE
Next.js: Module not found -> prop-types

### ISSUE THREAD

**Issue by totti-rdz** [KunwarVSuryavanshi/ReactToPDF#2]
Fist of all, thanks for your work!

I was trying out this package, but I'm having a hard time. I use Next 13.0.4. and I get the following message. 

<img width="1063" alt="Screenshot 2022-11-24 at 11 00 20" src="https://user-images.githubusercontent.com/88311102/203754792-70fb3600-4a7a-4cd7-b95e-ce6ac2f321b8.png">

This can be easily fixed by running

```bash
npm install prop-types
```

But it would be better to have that installed as a dev-dependency when installing your package. Unfortunately I do not know, how to fix this myself otherwise I would create a PR...

I tested and confirmed this behaviour on Next 12.2.0. But on React 18.2.0  (by create-react-app) it works.

Ps. In ReactToPDF.jsx on line 46 seems to be a typo, see [Link](https://github.com/KunwarVSuryavanshi/ReactToPDF/blob/613efef40e4515cd64f9ce94343d086ef6741aca/src/Component/ReactToPDF.jsx#L46).

`ReactToPDF.propTyppes = {` -> `ReactToPDF.propTypes = {`

**Comment by notKvS** [comment]
@totti-rdz the typo has been fixed and published .

For the propTypes, it has been added as a devDependencies only for the package. Maybe later in the evening I'll try with Nextjs sample project and check once.

**Comment by notKvS** [comment]
Since `ReactToPDF` is using prop-types in its implementation, and ```npm install``` does not install dev-dependecies by default for any npm package unless you run the npm install in that particular directory of the package hence it was giving that error, also it has been working with CRA because it adds `prop-types` package by default in node_modules.
So no error when using CRA.

Though package dependencies has been updated so it should not give prop-types error now.

**Comment by totti-rdz** [comment]
Thanks!!!
